spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.104:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.43.104

server:
  context-path: /sell
wechat:
  mpAppId: xxxxxxxxxxx
  mpAppSecret: xxxxxxxxx
resources:
  static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/,classpasth:/layui
project-url:
  sell: http://sell.com
